version: "3.7"

services:
  
  sme-grammar-checker:
    image: "lingsoft/gramdivvun:1.0.0-elg"
    environment: []
    restart: always



  restserver:
    image: registry.gitlab.com/european-language-grid/ilsp/elg-lt-service-execution-all:production-reactive
    command:
    - "--spring.webflux.base-path=/execution"
    - "--logging.level.elg.ltserviceexecution.api=WARN"
    - "--elg.ltservices.staticServices.sme-grammar-checker=http://sme-grammar-checker:8000/process"
    - "--elg.base.url=http://localhost:5080/execution"

    restart: always

  egistry_gitlab_com_european_language_grid_usfd_gui_ie_latest:
    image: "registry.gitlab.com/european-language-grid/usfd/gui-ie:latest"
    restart: always

  i18n:
    image: registry.gitlab.com/european-language-grid/platform/i18n-service:latest
    restart: always




  frontend:
    image: "nginx:alpine"
    ports:
    - "5080:80"
    volumes:
    - type: bind
      source: ./nginx-conf
      target: /etc/nginx/templates
    restart: always


